set MONGO_URI=xxxxxxxxxxxxxxxxxxxxx
set ADMIN_EMAIL=xxxxxxxxxxxxxxxxxxxxx
set ADMIN_PASSWORD=xxxxxxxxxxxxxxxxxxxxx
set JWT_SECRET=xxxxxxxxxxxxxxxxxxxxx
set PORT=xxxxxxxxxxxxxxxxxxxxx
Lymoner server.exe
